/*1*/
SELECT NOM_XEF ||' TIENE '|| NUM_ESTRELLAS || ' ESTRELLAS. ' AS "3 ESTRELLAS."  
FROM XEFS
WHERE NUM_ESTRELLAS = 3;

/*2*/
SELECT DISTINCT(NOMBRE_RECETA) ||' TIENE UNA VALORACION DE: '|| ESTRELLAS ||' ESTRELLAS.' AS "5 ESTRELLAS"
FROM RECEPTAS JOIN VALORACIONS USING (ID_RECEPTA)
WHERE ESTRELLAS = 5;

/*3*/
SELECT NOM_XEF ||' TIENE LA RECETA '|| NOMBRE_RECETA ||' CON '|| ESTRELLAS ||' ESTRELLAS Y LE HAN COMENTADO: '|| COMENTARIS  AS "XEF CON 5 ESTRELLAS"
FROM XEFS JOIN RECEPTAS ON (RECEPTA_XEF = ID_XEF) JOIN VALORACIONS USING (ID_RECEPTA)
WHERE ESTRELLAS = 5 AND COMENTARIS IS NOT NULL;

/*4*/
SELECT NOMBRE_RECETA ||' ES DEL XEF '|| NOM_XEF || ' Y TIENE '|| NUM_ESTRELLAS ||' ESTRELLAS.'  AS "POSTRES"
FROM RECEPTAS JOIN XEFS ON (ID_XEF = RECEPTA_XEF)
WHERE CATEGORIA LIKE 'Postres' AND CALORIES_PERS < 300;

/*5*/
SELECT NOM_XEF ||' TIENE UNA MEDIA DE '|| AVG(ID_RECEPTA) AS "ESTRELLAS"
FROM RECEPTAS JOIN XEFS ON (ID_XEF = RECEPTA_XEF) JOIN VALORACIONS USING (ID_RECEPTA)
WHERE NOM_XEF LIKE 'Antone'
GROUP BY NOM_XEF;

/*6*/
SELECT COUNT(ID_RECEPTA) ||' RECETAS UTILIZAN TOMATE COMO INGREDIENTE.' AS "USO DE TOMATE"
FROM CONSTAN
WHERE ID_INGREDIENT = (SELECT ID_INGREDIENT FROM INGREDIENTS WHERE NOM_INGREDIENT LIKE 'tomate');

/*7*/
SELECT  'MARIA HA CREADO '|| COUNT(ID_RECEPTA) ||' RECETAS.' AS "recetas maria"
FROM RECEPTAS
WHERE RECEPTA_XEF = (SELECT ID_XEF FROM XEFS WHERE NOM_XEF LIKE 'Maria');

SELECT NOM_XEF ||' HA CREADO LA RECETA: '|| NOMBRE_RECETA
FROM RECEPTAS JOIN XEFS ON (ID_XEF = RECEPTA_XEF)
WHERE NOM_XEF LIKE 'Maria';

/*8*/
SELECT NOMBRE_RECETA
FROM RECEPTAS 
WHERE NOMBRE_RECETA NOT IN (SELECT NOMBRE_RECETA 
FROM RECEPTAS JOIN CONSTAN USING (ID_RECEPTA) JOIN INGREDIENTS USING (ID_INGREDIENT)
WHERE NOM_INGREDIENT LIKE 'carne porcina');

/*9*/
SELECT NOMBRE_RECETA ||' CONTIENE '|| COUNT(NOM_INGREDIENT) || ' INGREDIENTES.' AS "CANTIDAD DE INGREDIENTES"
FROM RECEPTAS JOIN CONSTAN USING (ID_RECEPTA) JOIN INGREDIENTS USING (ID_INGREDIENT)
GROUP BY NOMBRE_RECETA;

/*10*/
SELECT NOMBRE_RECETA "RECETAS sin lacCTEOS"
FROM RECEPTAS JOIN CONSTAN USING (ID_RECEPTA) JOIN INGREDIENTS USING (ID_INGREDIENT)
WHERE TIPUS = 'vacuno' AND ID_RECEPTA NOT IN (SELECT ID_RECEPTA
FROM CONSTAN JOIN INGREDIENTS USING (ID_INGREDIENT)
WHERE TIPUS LIKE 'lacteo');

/*11*/
SELECT NOM_XEF ||' HA PARTICIPADO EN EL EVENTO: '|| NOM_ESDEVENIMENT ||' Y LE HAN PAGADO: '|| TARIFA || ' EUROS.'
FROM XEFS JOIN PARTICIPAN USING (ID_XEF) JOIN ESDEVENIMENTS USING (ID_ESDEVENIMENT);

/*12*/
SELECT NOM_ESDEVENIMENT ||' HAY INSCRITOS '|| COUNT(ID_USUARI) ||' USUARIOS.' AS "INSCRITOS A EVENTOS"
FROM INSCRITS JOIN ESDEVENIMENTS USING (ID_ESDEVENIMENT)
GROUP BY NOM_ESDEVENIMENT;

/*13*/
SELECT NOM_XEF ||' TIENE UN SALDO MAYOR A LA MEDIA DE : '|| TARIFA  ||' EUROS' AS "SALDO MAYOR A LA MEDIA"
FROM XEFS JOIN PARTICIPAN USING (ID_XEF)
HAVING TARIFA > (SELECT AVG(TARIFA) FROM PARTICIPAN) 
GROUP BY NOM_XEF, TARIFA;

/*14*/
SELECT NOM_ESDEVENIMENT ||' SE HIZO POR LA '|| ZONA_HORARIA || ' TUVO UNA DURACIÓN DE ' || DURADA || ' MINUTOS.' AS "SESIONES SHOW COOKING" 
FROM SESSIONS JOIN ESDEVENIMENTS USING (ID_ESDEVENIMENT);